from pathlib import Path
from typing import Literal

from ignis.utils.get_current_dir import get_current_dir
from nomix.utils.constants import CACHE_DIR, USER_CACHE_DIR

CURRENT_DIR = Path(get_current_dir())
MODE = Literal["light", "dark"]

# Where watch when a new wallpaper is setted
SWWW_CACHE = USER_CACHE_DIR / "swww"

# Output files generated by matugen
MATUGEN_LIGHT = CACHE_DIR / "matugen-light.scss"
MATUGEN_LIGHT.touch(exist_ok=True)

MATUGEN_DARK = CACHE_DIR / "matugen-dark.scss"
MATUGEN_DARK.touch(exist_ok=True)

MATUGEN_SCHEME = Literal[
    "content",
    "expressive",
    "fidelity",
    "fruit-salad",
    "monochrome",
    "neutral",
    "rainbow",
    "tonal-spot",
]
